version: "3"
services:
  node:
    container_name: "api-zoo"
    build: .
    command: "npm run start"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
      - POSTGRES_HOST=postgres
    expose:
      - "3000"
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - dev-net

  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    ports:
      - "5499:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Adm1n@23
      POSTGRES_DB: zoologico
    volumes:
      #- C:\\tmp\\docker-vol\\zoo-data:/var/lib/postgresql/data
      - ./docs/sql:/docker-entrypoint-initdb.d
    command: [ "postgres", "-c", "max_connections=1000" ]
    networks:
      - dev-net
volumes:
  postgres-data:

networks:
  dev-net:
    driver: bridge
